services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: astra
      POSTGRES_PASSWORD: astra_password
      POSTGRES_DB: astra_rails_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U astra -d astra_rails_development"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://astra:astra_password@db:5432/astra_rails_development
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data: