service: astra-rails
image: astra-rails

servers:
  web:
    - 107.21.151.93

registry:
  server: 609952815581.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "astra_rails_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/aws_ec2_key_pair.pem

accessories:
  db:
    image: postgres:16
    host: 107.21.151.93
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: astra_rails_production
        POSTGRES_USER: astra
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data